(cl:in-package ros_statistics_msgs-msg)
(cl:export '(NODE-VAL
          NODE
          HOST-VAL
          HOST
          URI-VAL
          URI
          PID-VAL
          PID
          WINDOW_START-VAL
          WINDOW_START
          WINDOW_STOP-VAL
          WINDOW_STOP
          SAMPLES-VAL
          SAMPLES
          THREADS-VAL
          THREADS
          CPU_LOAD_MEAN-VAL
          CPU_LOAD_MEAN
          CPU_LOAD_STD-VAL
          CPU_LOAD_STD
          CPU_LOAD_MAX-VAL
          CPU_LOAD_MAX
          VIRT_MEM_MEAN-VAL
          VIRT_MEM_MEAN
          VIRT_MEM_STD-VAL
          VIRT_MEM_STD
          VIRT_MEM_MAX-VAL
          VIRT_MEM_MAX
          REAL_MEM_MEAN-VAL
          REAL_MEM_MEAN
          REAL_MEM_STD-VAL
          REAL_MEM_STD
          REAL_MEM_MAX-VAL
          REAL_MEM_MAX
))