(cl:in-package ros_statistics_msgs-msg)
(cl:export '(HOSTNAME-VAL
          HOSTNAME
          IPADDRESS-VAL
          IPADDRESS
          WINDOW_START-VAL
          WINDOW_START
          WINDOW_STOP-VAL
          WINDOW_STOP
          SAMPLES-VAL
          SAMPLES
          CPU_LOAD_MEAN-VAL
          CPU_LOAD_MEAN
          CPU_LOAD_STD-VAL
          CPU_LOAD_STD
          CPU_LOAD_MAX-VAL
          CPU_LOAD_MAX
          PHYMEM_USED_MEAN-VAL
          PHYMEM_USED_MEAN
          PHYMEM_USED_STD-VAL
          PHYMEM_USED_STD
          PHYMEM_USED_MAX-VAL
          PHYMEM_USED_MAX
          PHYMEM_AVAIL_MEAN-VAL
          PHYMEM_AVAIL_MEAN
          PHYMEM_AVAIL_STD-VAL
          PHYMEM_AVAIL_STD
          PHYMEM_AVAIL_MAX-VAL
          PHYMEM_AVAIL_MAX
))