(cl:defpackage pr2_power_board-srv
  (:use )
  (:export
   "POWERBOARDCOMMAND2"
   "<POWERBOARDCOMMAND2-REQUEST>"
   "POWERBOARDCOMMAND2-REQUEST"
   "<POWERBOARDCOMMAND2-RESPONSE>"
   "POWERBOARDCOMMAND2-RESPONSE"
   "POWERBOARDCOMMAND"
   "<POWERBOARDCOMMAND-REQUEST>"
   "POWERBOARDCOMMAND-REQUEST"
   "<POWERBOARDCOMMAND-RESPONSE>"
   "POWERBOARDCOMMAND-RESPONSE"
  ))

